### PR TITLE
Improved integration with GitHub and other types of projects

### PR DESCRIPTION
**Pull request by brazabr**
- Added support for HTTP Basic Authentication (can be used with Personal Access Tokens to access private GitHub repositories)
- Added option to skip POT generation and import an existing file from repository/archive
- Added option to override GitHub branch or tag
- Modified settings page for better user experience (similar to standard WordPress inline edit)
- Improved settings page self-explanation using placeholders in fields

### CODE REVIEW

**Comment by Stiofan** [comment]
@brazabr Thanks for this, i needed authentication and was going to build it but your version works well :)
The only other thing i was thinking about building is for it to receive webhooks when a version is released and to auto extract when that happens. Has any one got any plans for this or wants this?

**Comment by toolstack** [comment]
@stiofan When I last spoke to @brazabr he mentioned he was going to be working on webhook next week.

**Comment by Stiofan** [comment]
Great!  @brazabr let me know if you need a hand.

**Comment by brazabr** [comment]
@Stiofan, I also do need webhook in our instance. Having private + webhook support is a must these days.

I should have it ready in next week or the other. The payload parser and the secret validation is already done in my local.

I just need an input on issue #4 to finish.

**Comment by brazabr** [comment]
I am closing this PR and we can work on #3.

**Pull request closed without merging**
